#ifndef VERSION_H
#define VERSION_H

#pragma once

#define APP_VERSION_MAJOR 0
#define APP_VERSION_MINOR 2
#define APP_BUILD_NUMBER 45

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

#define APP_VERSION_STRING \
TOSTRING(APP_VERSION_MAJOR) "." TOSTRING(APP_VERSION_MINOR) "." TOSTRING(APP_BUILD_NUMBER)

#endif // VERSION_H
